// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/category.dart';
import 'model/product.dart';
import 'model/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1804234227331903897),
      name: 'User',
      lastPropertyId: const IdUid(11, 4544174851941938934),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7235273234236947273),
            name: 'userId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 5144076723642793913)),
        ModelProperty(
            id: const IdUid(4, 2854935816122347427),
            name: 'username',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 944238387801549330),
            name: 'password',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2144832638566631917),
            name: 'uId',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(8, 2353302200629296688),
            name: 'firstName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 6856895876520465934),
            name: 'lastName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1978691702687235557),
            name: 'phoneNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 4544174851941938934),
            name: 'email',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 803300075456594274),
      name: 'Product',
      lastPropertyId: const IdUid(8, 6894476993731507213),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6920020617460914593),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8391578167469861979),
            name: 'productId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(2, 8136508235042784512)),
        ModelProperty(
            id: const IdUid(3, 7687622304847284293),
            name: 'room_price',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6852574431639635271),
            name: 'room_location',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6420164066604175231),
            name: 'image',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2457793205736042357),
            name: 'room_description',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 6540453669537444649),
      name: 'Category',
      lastPropertyId: const IdUid(5, 6784988289158001829),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2851417343352852447),
            name: 'cId',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 2104785640931135382),
            name: 'categoryId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(3, 5532225831525525996)),
        ModelProperty(
            id: const IdUid(5, 6784988289158001829),
            name: 'category_name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 6540453669537444649),
      lastIndexId: const IdUid(4, 2676902101768009065),
      lastRelationId: const IdUid(2, 5238031804794642045),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [2676902101768009065],
      retiredPropertyUids: const [
        7558905345642882435,
        761170410792412423,
        1548176190062946307,
        6001598375227869705,
        3849036958838273404,
        6511132067267747871,
        6894476993731507213
      ],
      retiredRelationUids: const [4802300515139935443, 5238031804794642045],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    User: EntityDefinition<User>(
        model: _entities[0],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.uId,
        setId: (User object, int id) {
          object.uId = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          final usernameOffset = object.username == null
              ? null
              : fbb.writeString(object.username!);
          final passwordOffset = object.password == null
              ? null
              : fbb.writeString(object.password!);
          final firstNameOffset = object.firstName == null
              ? null
              : fbb.writeString(object.firstName!);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          final phoneNumberOffset = object.phoneNumber == null
              ? null
              : fbb.writeString(object.phoneNumber!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          fbb.startTable(12);
          fbb.addOffset(0, userIdOffset);
          fbb.addOffset(3, usernameOffset);
          fbb.addOffset(5, passwordOffset);
          fbb.addInt64(6, object.uId);
          fbb.addOffset(7, firstNameOffset);
          fbb.addOffset(8, lastNameOffset);
          fbb.addOffset(9, phoneNumberOffset);
          fbb.addOffset(10, emailOffset);
          fbb.finish(fbb.endTable());
          return object.uId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User(
              firstName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              lastName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              username: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              password: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              phoneNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 4),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24),
              uId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));

          return object;
        }),
    Product: EntityDefinition<Product>(
        model: _entities[1],
        toOneRelations: (Product object) => [],
        toManyRelations: (Product object) => {},
        getId: (Product object) => object.id,
        setId: (Product object, int id) {
          object.id = id;
        },
        objectToFB: (Product object, fb.Builder fbb) {
          final productIdOffset = object.productId == null
              ? null
              : fbb.writeString(object.productId!);
          final room_priceOffset = object.room_price == null
              ? null
              : fbb.writeString(object.room_price!);
          final room_locationOffset = object.room_location == null
              ? null
              : fbb.writeString(object.room_location!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final room_descriptionOffset = object.room_description == null
              ? null
              : fbb.writeString(object.room_description!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, productIdOffset);
          fbb.addOffset(2, room_priceOffset);
          fbb.addOffset(3, room_locationOffset);
          fbb.addOffset(5, imageOffset);
          fbb.addOffset(6, room_descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Product(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              productId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              room_price: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              room_location: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              room_description: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14));

          return object;
        }),
    Category: EntityDefinition<Category>(
        model: _entities[2],
        toOneRelations: (Category object) => [],
        toManyRelations: (Category object) => {},
        getId: (Category object) => object.cId,
        setId: (Category object, int id) {
          object.cId = id;
        },
        objectToFB: (Category object, fb.Builder fbb) {
          final categoryIdOffset = object.categoryId == null
              ? null
              : fbb.writeString(object.categoryId!);
          final category_nameOffset = object.category_name == null
              ? null
              : fbb.writeString(object.category_name!);
          fbb.startTable(6);
          fbb.addInt64(0, object.cId);
          fbb.addOffset(1, categoryIdOffset);
          fbb.addOffset(4, category_nameOffset);
          fbb.finish(fbb.endTable());
          return object.cId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Category(
              categoryId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              category_name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              cId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.userId]
  static final userId = QueryStringProperty<User>(_entities[0].properties[0]);

  /// see [User.username]
  static final username = QueryStringProperty<User>(_entities[0].properties[1]);

  /// see [User.password]
  static final password = QueryStringProperty<User>(_entities[0].properties[2]);

  /// see [User.uId]
  static final uId = QueryIntegerProperty<User>(_entities[0].properties[3]);

  /// see [User.firstName]
  static final firstName =
      QueryStringProperty<User>(_entities[0].properties[4]);

  /// see [User.lastName]
  static final lastName = QueryStringProperty<User>(_entities[0].properties[5]);

  /// see [User.phoneNumber]
  static final phoneNumber =
      QueryStringProperty<User>(_entities[0].properties[6]);

  /// see [User.email]
  static final email = QueryStringProperty<User>(_entities[0].properties[7]);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// see [Product.id]
  static final id = QueryIntegerProperty<Product>(_entities[1].properties[0]);

  /// see [Product.productId]
  static final productId =
      QueryStringProperty<Product>(_entities[1].properties[1]);

  /// see [Product.room_price]
  static final room_price =
      QueryStringProperty<Product>(_entities[1].properties[2]);

  /// see [Product.room_location]
  static final room_location =
      QueryStringProperty<Product>(_entities[1].properties[3]);

  /// see [Product.image]
  static final image = QueryStringProperty<Product>(_entities[1].properties[4]);

  /// see [Product.room_description]
  static final room_description =
      QueryStringProperty<Product>(_entities[1].properties[5]);
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// see [Category.cId]
  static final cId = QueryIntegerProperty<Category>(_entities[2].properties[0]);

  /// see [Category.categoryId]
  static final categoryId =
      QueryStringProperty<Category>(_entities[2].properties[1]);

  /// see [Category.category_name]
  static final category_name =
      QueryStringProperty<Category>(_entities[2].properties[2]);
}
